---
title: "sooty-watch"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sooty-watch}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(dplyr)
```

Set some env vars we need

```{r vars}
Sys.setenv("AWS_NO_SIGN_REQUEST" = "YES")
Sys.setenv("AWS_S3_ENDPOINT" = "projects.pawsey.org.au")
Sys.setenv("AWS_VIRTUAL_HOSTING" = "FALSE")
```

```{r setup}
library(sooty.watch)
watch_curated()

watch_buckets()
```

For each dataset, let's get the first and last and plot. 


```{r datasets}
library(dplyr)
datasets <- group_by(sooty::sooty_files(), Dataset)

th <- function(x, ...) rbind(head(x, 1L), tail(x, 1L))
read1 <- function(x) {
  out <- terra::rast(x)[[1]]
  names(out) <- substr(names(out), 1, 24)
out
}
plotfun <- function(x) {

  plot(x[[1]], main = format(time(x[[1]]))); plot(x[[2]], main = format(time(x[[2]])))
}
library(terra)
ctch <- dplyr::group_map(datasets, \(.x, ...) try(plotfun(lapply(th(.x)$source, read1))))

```


